GET http://localhost:3000/api/vehicles HTTP/1.1

###

GET http://localhost:3000/api/vehicle?id=245 HTTP/1.1

###

POST http://localhost:3000/api/vehicle HTTP/1.1
content-type: application/json

{
    "description": "sample vehicle",
    "regNumber": "CAA 780-123"
}

###
POST http://localhost:3000/api/refuel HTTP/1.1
content-type: application/json

{
    "vehicleId" : 245, 
    "liters" : 30, 
    "amount" : 675, 
    "distance" :  56003, 
    "filledUp" : true
}

###
POST http://localhost:3000/api/refuel HTTP/1.1
content-type: application/json

{
    "vehicleId" : 245, 
    "liters" : 20, 
    "amount" : 475, 
    "distance" : 56423, 
    "filledUp" : true
}

###

###